### ISSUE TITLE
At least python>=3.10 required for unit-tests to pass

### ISSUE THREAD

**Issue by Lodewic** [trelliscope/trelliscope-py#14]
# Package does not pass tests for python < 3.10

Running unit-tests on the `main` branch using multiple python version I found that you require at least python>=3.10.
Most of the issues are because of usage of functions in `importlib` that were introduced in more recent python versions. But, not all issues are with importlib.

---

When running on python 3.8, these are the failed tests:

```
FAILED trelliscope/tests/test_html_utils.py::test_write_javascript - AttributeError: module 'importlib.resources' has no attribute 'files'
FAILED trelliscope/tests/test_panels.py::test_panels_setup - AttributeError: module 'importlib.resources' has no attribute 'files'
FAILED trelliscope/tests/test_panels.py::test_set_panel_options - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_trelliscope.py::test_standard_setup - AttributeError: module 'importlib.resources' has no attribute 'files'
FAILED trelliscope/tests/test_trelliscope.py::test_write_javascript - AttributeError: module 'importlib.resources' has no attribute 'files'
FAILED trelliscope/tests/test_trelliscope.py::test_infer_panels - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_utils.py::test_get_file_path - AssertionError: assert '/test1/test2\\file.jsonp' == '/test1/test2/file.jsonp'
FAILED trelliscope/tests/test_utils.py::test_check_image_extension - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_utils.py::test_get_extension - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_utils.py::test_extension_matches - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_utils.py::test_extension_matches_match_case - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_utils.py::test_find_image_columns - AttributeError: 'str' object has no attribute 'removeprefix'
FAILED trelliscope/tests/test_utils.py::test_is_image_column - AttributeError: 'str' object has no attribute 'removeprefix'
```

---

When running on python 3.9, these are the failed tests:

```
FAILED trelliscope/tests/test_html_utils.py::test_write_javascript - TypeError: expected str, bytes or os.PathLike object, not NoneType
FAILED trelliscope/tests/test_panels.py::test_panels_setup - TypeError: expected str, bytes or os.PathLike object, not NoneType
FAILED trelliscope/tests/test_trelliscope.py::test_standard_setup - TypeError: expected str, bytes or os.PathLike object, not NoneType
FAILED trelliscope/tests/test_trelliscope.py::test_write_javascript - TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Automated testing

I am developing a PR that adds automated testing using Github Actions across Windows + Linux and multiple python versions. 
The output of such a test is here: [https://github.com/Lodewic/trelliscope-py/actions/runs/7679548173](https://github.com/Lodewic/trelliscope-py/actions/runs/7679548173)

However, these output of this specific test is on a branch that already has more changes than `main` branch. But it will still be good to add automated testing to ensure tests are passing across python version in a similar way.

**Comment by Lodewic** [comment]
Happy to contribute and looking forward to actively using trelliscope from python!

I can make a PR for alternative ways to include and load package data. For python >= 3.8 this is doable, for python 3.7 I think things become too complicated to support because of pandas.

So my question is, do you want to support python 3.7 at all? I ask because pandas 1.5.0 does not  support python 3.7. And with pandas being a pretty important dependency, I would suggest also sticking to 3.8+ 
(https://pandas.pydata.org/pandas-docs/version/1.5/getting_started/install.html#python-version-support)

**Comment by sburton42** [comment]
I agree, I think supporting Python 3.8 will be sufficient. Thanks!

**Comment by sburton42** [comment]
It looks like the issues for the Windows unit tests is in the "install dependencies" step. Perhaps future investigation could determine the issue there and address it. It's possible it is with a third party library that could be cached differently. But I wonder if it's related to collecting and building the Trelliscope code.

**Comment by sburton42** [comment]
I'm going to go ahead and close this issue and we can create a new one for the delay in the windows unit tests later if desired.
